const movies = [
  {
    id: 1,
    title: 'GM Onix',
    ranking: "1º",
    units: '241.214',
    imagePath: 'images/onix.png',
    price: '36.900',
    specs: 'Não é à toa que o Chevrolet Onix é o veículo líder de vendas no Brasil há 3 anos: com muita tecnologia de conectividade, design moderno e recursos que garantem conforto interno, o carro Onix hatch vai surpreender você.',
    bookmarked: true,
  },
  {
    id: 2,
    title: 'Ford Ka',
    ranking: "2º",
    units: '104.331',
    imagePath: 'images/ka.png',
    price: "35.760",
    specs: "",
    bookmarked: false,
  },
  {
    id: 3,
    title: 'Hyundai HB20',
    ranking: "3º",
    units: '101.590',
    imagePath: 'images/hb20.png',
    price: "39.900",
    specs: "",
    bookmarked: true,
  },
  {
    id: 4,
    title: 'Renault Kwid',
    ranking: "4º",
    units: '85.117',
    imagePath: 'images/kwid.png',
    price: "34.990",
    specs: "",
    bookmarked: false,
  },
  {
    id: 5,
    title: 'VW Gol',
    ranking: '5º',
    units: '81.285',
    imagePath: 'images/gol.png',
    price: "38.280",
    specs: "",
    bookmarked: true,
  },
];

export default movies;
