const movies = [{
  id: 1,
  title: 'GM Onix',
  ranking: '1º',
  units: '241.214',
  imagePath: 'src/images/onix.png',
  price: '36.900',
  specs: 'Na versão 1.4, modelo passa a contar com a oferta de transmissão automática de seis velocidades; Seu porte parrudo passa a impressão de se tratar de um veículo de segmento superior. O motor 1.0 também dá boa mobilidade do novo hatch da Chevrolet, que parece pesado demais para litros de menos',
  bookmarked: true,
},
{
  id: 2,
  title: 'Ford Ka',
  ranking: '2º',
  units: '104.331',
  imagePath: 'src/images/ka.png',
  price: '35.760',
  specs: '',
  bookmarked: false,
},
{
  id: 3,
  title: 'Hyundai HB20',
  ranking: '3º',
  units: '101.590',
  imagePath: 'src/images/hb20.png',
  price: '39.900',
  specs: '',
  bookmarked: true,
},
{
  id: 4,
  title: 'Renault Kwid',
  ranking: '4º',
  units: '85.117',
  imagePath: 'src/images/kwid.png',
  price: '34.990',
  specs: '',
  bookmarked: false,
},
{
  id: 5,
  title: 'VW Gol',
  ranking: '5º',
  units: '81.285',
  imagePath: 'src/images/gol.png',
  price: '38.280',
  specs: '',
  bookmarked: true,
},
];

export default movies;
